# Generated by Django 4.2.4 on 2024-12-07 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ContentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewcountmodel',
            unique_together={('content', 'user')},
        ),
        migrations.CreateModel(
            name='FavoritePosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContentApp.contentmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
