# Generated by Django 4.2.4 on 2024-12-04 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='forgot_pass_active_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_login_active_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
    ]
